site_name: MPEL
pages:
- Home: index.md
- Primer:
    - 'Basic Ideas': basics.md
    - 'Algorithms': algos.md
- Documentation:
    - 'Getting Started': start.md
    - 'API Reference': doc.md
    - 'Tutorials': tut.md
- Troubleshooting: trouble.md
- Contact Us: contact.md
theme: united
