site_name: MPEL
site_url: https://lakshayg.github.io/mpel
repo_url: https://github.com/lakshayg/mpel
site_description: Documentation for the Motion Planning and Experimentation Library (MPEL)
site_author: Lakshay Garg
pages:
- Home: index.md
- Primer:
    - 'Basic Ideas': basics.md
    - 'Algorithms': algos.md
- Documentation:
    - 'Getting Started': start.md
    - 'API Reference': doc.md
    - 'Tutorials': tut.md
- Troubleshooting: trouble.md
- Contact Us: contact.md
site_favicon: favicon.ico
theme: united
